; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^6.6.0
board = esp32dev
framework = arduino
lib_deps = 
	/home/smr/projects/qpcpp_esp32
	signalk/SensESP@^3.1.1
monitor_speed = 115200
build_flags = 
	-D QP_CPU_NUM=1
	-D CONFIG_QP_IDLE_YIELD
	-D Q_SPY
  -D CORE_DEBUG_LEVEL=0
board_build.partitions = min_spiffs.csv

